import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import vuetify from "./plugins/vuetify";
import "material-design-icons-iconfont/dist/material-design-icons.css";
import "@/styles/EstilosGenerales.css";
const app = createApp(App);
app.use(router);
app.use(vuetify);
app.mount("#app");
